### PR TITLE
Change to theme submodule

### PR DESCRIPTION
**Pull request by djwfyi**
- Removes the existing theme
- Adds the hugo-docs-theme repo as a submodule.
- Updates config.toml to point to the new theme directory.

### CODE REVIEW

**Comment by rushenn** [comment]
@djwfyi Initially, the submodule files were not getting pulled with the basic git `pull` or `rebase` commands. I had to use the following command to fix this.

```
git submodule update --init --recursive
```

Do you thing it's better to add this in the README?

**Comment by rushenn** [comment]
@djwfyi File paths in both NPM scripts and `tailwind.config.js` seem broken. I'll send a PR to
[hugo-docs-theme](https://github.com/miniohq/hugo-docs-theme) to fix this.

**Review by rushenn — APPROVED** [review]
LGTM

**Comment by djwfyi** [comment]
@rushenn 
Yes, I'll add in submodule instructions before merging. Good idea.

**Pull request merged**
