### PR TITLE
Replace references to `kes tool` command.

### LINKED ISSUE #61: Dangling reference to `kes tool` in TLS Proxy config page
https://min.io/docs/kes/concepts/tls-proxy/#update-the-kes-configuration

A community user pointed out we still have an old reference to `kes tool identity of` on this page.

Needs to be updated to `kes identity of`

Might as well do a `grep` pass to make sure we haven't missed it anywhere else.

### PR DESCRIPTION
**Pull request by djwfyi**
Closes #61

Fixes references to `kes tool` throughout the docs.

Staged:
- http://docs-nginx.minio.training:31080/kes-docs/kes-tool/concepts/tls-proxy/

### CODE REVIEW

**Comment by feorlen** [comment]
While you are in here, this admonition at the bottom of tls-proxy.rst is horked
```
     {{< admonition type="note">}}
     You can only perform operations if the policy attached to your identity allows them.
     If you act as the `root` identity because you have set `KES_CLIENT_TLS_CERT_FILE` to the root certificate file, then you should be able to perform any operation. 
     If you act as another identity that does not have the policy permission to list all policies then the KES server will reject the request with a `prohibited by policy` error.
     {{< /admonition >}}
```

**Review by ravindk89 — APPROVED** [review]
Nicely grepped , LGTM mod Andrea's note

**Comment by feorlen** [comment]
There's at least one other drive by change, just a sec while I finish scrolling through

**Comment by feorlen** [comment]
Google Cloud Secret Manager
> GCP let’s you download a JSON file with the following structure:

**Comment by feorlen** [comment]
yay fixing random bugs 🎉

**Review by feorlen — APPROVED** [review]
💯 
noted some other random things worth fixing while you are here

**Pull request merged**
