### PR TITLE
Add CLI docs

### LINKED ISSUE #13: Document KES CLI
The KES CLI is not currently documented anywhere.
Add CLI docs.

Reference https://github.com/minio/kes/blob/master/cmd/kes/main.go

### PR DESCRIPTION
**Pull request by djwfyi**
Adds the KES CLI docs.
Closes #13 

Clone this PR locally.
With Hugo installed, run `npm start` to build and visit `localhost:1313` to see the docs in your browser.

See the repo's README for more detailed instructions.

### CODE REVIEW

**Comment by djwfyi** [comment]
@rushenn Take a look at the left nav with the CLI docs added.
The KES CLI section has it's own _index page, which renders as a link that is not bolded.
We need to mirror how the MinIO cli docs work, with nested docs hidden until the parent is selected.

There's also some odd spacing between headings, I think between folders that have just an "_index" and those that have other files as well.

**Comment by rushenn** [comment]
@djwfyi Can you resolve the conflicts?

**Comment by djwfyi** [comment]
@rushenn Conflicts resolved

**Comment by rushenn** [comment]
@djwfyi I will send a new PR to address the left menu issues.

**Review by rushenn — APPROVED** [review]
LGTM

**Pull request merged**
