### PR TITLE
Implement MinIO docs design

### PR DESCRIPTION
**Pull request by rushenn**
This is the phase one of the implementation process. Here I have implemented the base UI with minimal functional features. 

**TODO:**
- ~~Dark UI~~
- ~~Read Mode~~
- Responsive UI

If you detected any design flaws, kindly disregard them since the implementation is still in the works.

**How to test:**
I'm using Tailwind to build the CSS, in order to test and modify the theme, use the scripts listed below.

- Run `npm start` to build CSS and serve HUGO.
- Run `npm run dev` before making any CSS class name changes on HTML.

### CODE REVIEW

**Comment by rushenn** [comment]
@ravindk89 Should we implement the Platform navigation on KES docs as well?

Screenshot 2023-02-06 at 19 34 09

**Comment by ravindk89** [comment]
Not yet I think. Let's start with focusing on Linux. For K8s we can just
point to the operator.

If we have a lot of users asking for guidance on k8s kes without minio we
can revisit

**Comment by ravindk89** [comment]
No, I think we are ok to just focus on KES + Linux and docker.

For all the others we can point to the core docs.

**Comment by djwfyi** [comment]
@rushenn This is looking great! Thanks for your work on it!

I understand it's still a work in progress, but it'll be easier to start really ramping up KES doc migration and make better Hugo-specific implementation choices with the design in place.

## Design questions
- It looks like the post container width is limited to about 60% of the space to the right of the gray navigation bar area when I fullscreen it on desktop. Is the right area reserved for something? The space seems too wide just for a page TOC.

image


## Additional things we need to think through

@ravindk89 

- Does the main top nav Docs link need to become a dropdown for `MinIO` and `Key Encryption Service`? I think this was the intent when we were talking about this split. Keeping in mind that we'll most likely be using this same design to also implement DirectPV docs very soon.
- Alternatively, create a separate docs landing page where users can then select the product. But this would be outside of either Sphinx or Hugo, I suppose. Perhaps just on the web design team.
- Do we want Algolia to fully integrate across all docs, or do we want to set up separate crawlers/search results for KES specifically? That is, do we want KES results available from upstream Kubernetes MinIO and vice versa?

**Comment by djwfyi** [comment]
Also, note @ravindk89 if/when you test it, you need to be in the `Source` folder and run the npm commands from there.

**Review by djwfyi — APPROVED** [review]
LGTM for phase 1.

**Comment by rushenn** [comment]
Thank you for the feedback @djwfyi. Container width should be full width. I'll note this issue and make sure to fix it on the phase 2 PR.

**Comment by rushenn** [comment]
@ravindk89 @djwfyi Added dark theme. I'd really appreciate it If you could give it another look.

**Comment by djwfyi** [comment]
Dark mode and the footer width look great.
Do you want me to merge this and do the responsive UI work in a separate PR, or keep this one open to do it all here?

**Comment by rushenn** [comment]
@djwfyi Can you merge this first? I will send a new PR for the responsive part.

**Pull request merged**
